<a href="https://colab.research.google.com/github/nigoda/machine_learning/blob/main/06_BatchingTensorsWithPadding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Batching dataset elements**

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
inc_dataset = tf.data.Dataset.range(100)
dec_dataset = tf.data.Dataset.range(0, -100, -1)
dataset = tf.data.Dataset.zip((inc_dataset, dec_dataset))
batched_dataset = dataset.batch(4)

for batch in batched_dataset.take(4):
  print([arr.numpy() for arr in batch])

[array([0, 1, 2, 3]), array([ 0, -1, -2, -3])]
[array([4, 5, 6, 7]), array([-4, -5, -6, -7])]
[array([ 8,  9, 10, 11]), array([ -8,  -9, -10, -11])]
[array([12, 13, 14, 15]), array([-12, -13, -14, -15])]


In [ ]:
batched_dataset

<BatchDataset shapes: ((None,), (None,)), types: (tf.int64, tf.int64)>

In [ ]:
batched_dataset = dataset.batch(7, drop_remainder=True)
batched_dataset
for batch in batched_dataset.take(4):
  print([arr.numpy() for arr in batch])

[array([0, 1, 2, 3, 4, 5, 6]), array([ 0, -1, -2, -3, -4, -5, -6])]
[array([ 7,  8,  9, 10, 11, 12, 13]), array([ -7,  -8,  -9, -10, -11, -12, -13])]
[array([14, 15, 16, 17, 18, 19, 20]), array([-14, -15, -16, -17, -18, -19, -20])]
[array([21, 22, 23, 24, 25, 26, 27]), array([-21, -22, -23, -24, -25, -26, -27])]


### **Batching tensors with padding**

In [ ]:
dataset = tf.data.Dataset.range(100)
dataset = dataset.map(lambda x: tf.fill([tf.cast(x, tf.int32)],x))
dataset = dataset.padded_batch(4, padded_shapes=(None,))

for batch in dataset.take(2):
  print(batch.numpy())
  print()

[[0 0 0]
 [1 0 0]
 [2 2 0]
 [3 3 3]]

[[4 4 4 4 0 0 0]
 [5 5 5 5 5 0 0]
 [6 6 6 6 6 6 0]
 [7 7 7 7 7 7 7]]

