<a href="https://colab.research.google.com/github/nigoda/machine_learning/blob/main/10_Heart_disease_pandasdataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Read data using pandas**

In [ ]:
import pandas as pd
import tensorflow as tf

In [ ]:
csv_file = tf.keras.utils.get_file('heart.csv', 'https://storage.googleapis.com/download.tensorflow.org/data/heart.csv')

Read the csv file using pandas.

In [ ]:
df = pd.read_csv(csv_file)
df.head()

age  sex  cp  trestbps  chol  ...  oldpeak  slope  ca        thal  target
0   63    1   1       145   233  ...      2.3      3   0       fixed       0
1   67    1   4       160   286  ...      1.5      2   3      normal       1
2   67    1   4       120   229  ...      2.6      2   2  reversible       0
3   37    1   3       130   250  ...      3.5      3   0      normal       0
4   41    0   2       130   204  ...      1.4      1   0      normal       0

[5 rows x 14 columns]

In [ ]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal         object
target        int64
dtype: object

Convert **thal** column which is an **object** in the dataframe to a discrete numerical value.

In [ ]:
df['thal'] = pd.Categorical(df['thal'])
df['thal'] = df.thal.cat.codes
df.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   1       145   233    1  ...      0      2.3      3   0     2       0
1   67    1   4       160   286    0  ...      1      1.5      2   3     3       1
2   67    1   4       120   229    0  ...      1      2.6      2   2     4       0
3   37    1   3       130   250    0  ...      0      3.5      3   0     3       0
4   41    0   2       130   204    0  ...      0      1.4      1   0     3       0

[5 rows x 14 columns]

### **Load data using tf.data.Dataset**

Use tf.data.Dataset.from_tensor_slices to read the values from a pandas dataframe.

One of the advanatage of using tf.data.Dataset is it allows you to write simple, highly efficient data pipelines. Read the loading data guide to find out more.

In [ ]:
target = df.pop('target')

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices((df.values, target.values))

In [ ]:
for feat, targ in dataset.take(5):
  print('Features: {}, Target: {}'.format(feat, targ))

Features: [ 63.    1.    1.  145.  233.    1.    2.  150.    0.    2.3   3.    0.
   2. ], Target: 0
Features: [ 67.    1.    4.  160.  286.    0.    2.  108.    1.    1.5   2.    3.
   3. ], Target: 1
Features: [ 67.    1.    4.  120.  229.    0.    2.  129.    1.    2.6   2.    2.
   4. ], Target: 0
Features: [ 37.    1.    3.  130.  250.    0.    0.  187.    0.    3.5   3.    0.
   3. ], Target: 0
Features: [ 41.    0.    2.  130.  204.    0.    2.  172.    0.    1.4   1.    0.
   3. ], Target: 0


Since a pd.Series implements the **_ _ _array_ _ _** protocol it can be used transparently nearly anywhere you would use a **np.array** or a **tf.Tensor**

In [ ]:
tf.constant(df['thal'])

<tf.Tensor: shape=(303,), dtype=int8, numpy=
array([2, 3, 4, 3, 3, 3, 3, 3, 4, 4, 2, 3, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3,
       3, 4, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 4, 2, 4, 3, 4, 3, 4, 4,
       2, 3, 3, 4, 3, 3, 4, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 4,
       4, 2, 3, 3, 4, 3, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 3, 3, 4, 4, 4,
       3, 3, 4, 3, 4, 4, 3, 4, 3, 3, 3, 4, 3, 4, 4, 3, 3, 4, 4, 4, 4, 4,
       3, 3, 3, 3, 4, 3, 4, 3, 4, 4, 3, 3, 2, 4, 4, 2, 3, 3, 4, 4, 3, 4,
       3, 3, 4, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 3, 2,
       4, 4, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 2, 2, 4, 3, 4, 2, 4, 3,
       3, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 2, 2, 4, 3, 4, 3, 2, 4, 3, 3, 2,
       4, 4, 4, 4, 3, 0, 3, 3, 3, 3, 1, 4, 3, 3, 3, 4, 3, 4, 3, 3, 3, 4,
       3, 3, 4, 4, 4, 4, 3, 3, 4, 3, 4, 3, 4, 4, 3, 4, 4, 3, 4, 4, 3, 3,
      

In [ ]:
train_dataset = dataset.shuffle(len(df)).batch(1)

# Create and train a model

In [ ]:
def get_compiled_model():
  model = tf.keras.Sequential([
     tf.keras.layers.Dense(10, activation = 'relu'),
     tf.keras.layers.Dense(10, activation = 'relu'),
     tf.keras.layers.Dense(1)
  ])

  model.compile(optimizer = 'adam',
                loss = tf.keras.losses.BinaryCrossentropy(from_logits=True),
                metrics=['accuracy'])
  return model

In [ ]:
model = get_compiled_model()
model.fit(train_dataset, epochs=15)

Epoch 1/15
303/303 [==============================] - 1s 981us/step - loss: 3.2296 - accuracy: 0.7430
Epoch 2/15
303/303 [==============================] - 0s 1ms/step - loss: 0.5375 - accuracy: 0.7507
Epoch 3/15
303/303 [==============================] - 0s 1ms/step - loss: 0.5047 - accuracy: 0.7537
Epoch 4/15
303/303 [==============================] - 0s 1ms/step - loss: 0.5435 - accuracy: 0.7196
Epoch 5/15
303/303 [==============================] - 0s 1ms/step - loss: 0.5505 - accuracy: 0.7069
Epoch 6/15
303/303 [==============================] - 0s 998us/step - loss: 0.5033 - accuracy: 0.7533
Epoch 7/15
303/303 [==============================] - 0s 1ms/step - loss: 0.5134 - accuracy: 0.7314
Epoch 8/15
303/303 [==============================] - 0s 1ms/step - loss: 0.4717 - accuracy: 0.7492
Epoch 9/15
303/303 [==============================] - 0s 1ms/step - loss: 0.4656 - accuracy: 0.7224
Epoch 10/15
303/303 [==============================] - 0s 1ms/step - loss: 0.4942 - accuracy: 0.

### Alternative to feature columns

Passing a dictionary as an input to a model is as easy as creating a matching dictionary of tf.keras.layers.Input layers,applying any pre-processing and stacking them up using the function api. You can use this as an alternative to feature columns.

In [ ]:
inputs = {key: tf.keras.layers.Input(shape=(), name=key) for key in df.keys()}
x = tf.stack(list(inputs.values()), axis=-1)

x = tf.keras.layers.Dense(10, activation='relu')(x)
output = tf.keras.layers.Dense(1)(x)

model_func = tf.keras.Model(inputs=inputs, outputs=output)

model_func.compile(optimizer='adam',
                   loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                   metrics=['accuracy'])

In [ ]:
dict_slices = tf.data.Dataset.from_tensor_slices((df.to_dict('list'), target.values)).batch(16)

In [ ]:
for dict_slice in dict_slices.take(1):
  print(dict_slice)

({'age': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([63, 67, 67, 37, 41, 56, 62, 57, 63, 53, 57, 56, 56, 44, 52, 57],
      dtype=int32)>, 'sex': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1], dtype=int32)>, 'cp': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 4, 4, 3, 2, 2, 4, 4, 4, 4, 4, 2, 3, 2, 3, 3], dtype=int32)>, 'trestbps': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([145, 160, 120, 130, 130, 120, 140, 120, 130, 140, 140, 140, 130,
       120, 172, 150], dtype=int32)>, 'chol': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([233, 286, 229, 250, 204, 236, 268, 354, 254, 203, 192, 294, 256,
       263, 199, 168], dtype=int32)>, 'fbs': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int32)>, 'restecg': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0, 0], dtype=int32)>, 'thalach': <tf.Tensor: shape=(16

In [ ]:
model_func.fit(dict_slices, epochs=15)

Epoch 1/15
19/19 [==============================] - 0s 2ms/step - loss: 1.0678 - accuracy: 0.6865
Epoch 2/15
19/19 [==============================] - 0s 2ms/step - loss: 1.0170 - accuracy: 0.7063
Epoch 3/15
19/19 [==============================] - 0s 2ms/step - loss: 0.9773 - accuracy: 0.7261
Epoch 4/15
19/19 [==============================] - 0s 2ms/step - loss: 0.9446 - accuracy: 0.7294
Epoch 5/15
19/19 [==============================] - 0s 2ms/step - loss: 0.9158 - accuracy: 0.7294
Epoch 6/15
19/19 [==============================] - 0s 2ms/step - loss: 0.8894 - accuracy: 0.7426
Epoch 7/15
19/19 [==============================] - 0s 2ms/step - loss: 0.8645 - accuracy: 0.7525
Epoch 8/15
19/19 [==============================] - 0s 2ms/step - loss: 0.8409 - accuracy: 0.7558
Epoch 9/15
19/19 [==============================] - 0s 2ms/step - loss: 0.8184 - accuracy: 0.7525
Epoch 10/15
19/19 [==============================] - 0s 2ms/step - loss: 0.7970 - accuracy: 0.7624
Epoch 11/15
19/19 [